In [1]:
import pandas as pd
import sqlite3
import json

In [2]:
customers = pd.read_csv(r"C:\Users\DELL\Desktop\guvipro\data\customers.csv")
accounts = pd.read_csv(r"C:\Users\DELL\Desktop\guvipro\data\accounts.csv")
transactions =pd.read_csv(r"C:\Users\DELL\Desktop\guvipro\data\transactions.csv")
loans =pd.read_csv(r"C:\Users\DELL\Desktop\guvipro\data\customers.csv")
credit_cards = pd.read_json(r"C:\Users\DELL\Desktop\guvipro\data\credit_cards.json")
branches = pd.read_csv(r"C:\Users\DELL\Desktop\guvipro\data\branches.csv")
support_tickets = pd.read_json(r"C:\Users\DELL\Desktop\guvipro\data\support_tickets.json")

In [3]:
print(customers.head())

  customer_id              name gender  age            city account_type  \
0       C0001    Richard Wilson      M   65   Kimberlyburgh      Savings
1       C0002      Holly Parker      F   41      Port David      Current
2       C0003     Megan Alvarez      M   46  West Laurieton      Savings
3       C0004  Nicholas Stewart      F   39        Amyville      Current
4       C0005  Douglas Anderson      M   70   New Craigport      Current

    join_date
0  2023-08-27
1  2023-12-08
2  2022-05-25
3  2020-11-30
4  2023-01-29

In [4]:
print(accounts.head())

  customer_id  account_balance         last_updated
0       C0001        293729.87  2025-05-24 09:46:29
1       C0002        150735.15  2025-05-24 09:46:29
2       C0003        170156.21  2025-05-24 09:46:29
3       C0004        311383.96  2025-05-24 09:46:29
4       C0005         60320.75  2025-05-24 09:46:29

In [5]:
print(transactions.head())

   txn_id customer_id    txn_type    amount             txn_time   status
0  T00001       C0363     deposit  44442.71  2025-02-14 06:26:00  success
1  T00002       C0432     deposit  15737.59  2025-03-27 07:21:21  success
2  T00003       C0084  withdrawal  82150.70  2024-07-31 18:28:06  success
3  T00004       C0067  withdrawal  20313.86  2024-11-11 12:18:47  success
4  T00005       C0485  withdrawal  74536.08  2025-04-15 10:52:59  success

In [6]:
print(loans.head())

  customer_id              name gender  age            city account_type  \
0       C0001    Richard Wilson      M   65   Kimberlyburgh      Savings
1       C0002      Holly Parker      F   41      Port David      Current
2       C0003     Megan Alvarez      M   46  West Laurieton      Savings
3       C0004  Nicholas Stewart      F   39        Amyville      Current
4       C0005  Douglas Anderson      M   70   New Craigport      Current

    join_date
0  2023-08-27
1  2023-12-08
2  2022-05-25
3  2020-11-30
4  2023-01-29

In [7]:
print(credit_cards.head())

   Card_ID  Customer_ID  Account_ID                               Branch  \
0        1         1559        2090                     Perez Ltd Branch
1        2         1160        2221                    Miller Inc Branch
2        3         1297        2082   Miles, Patterson and Murray Branch
3        4         1333        2058  Shepard, Gonzales and Cooper Branch
4        5         1371        2225                    Wilson PLC Branch

        Card_Number Card_Type Card_Network  Credit_Limit  Current_Balance  \
0  4960013389083863  Business         Visa        178393         39819.23
1  6511615594078161  Platinum        RuPay        416026        175818.58
2  6316475255341928      Gold        RuPay        419398         29171.29
3  3305641395376724      Gold         Amex        385544        265316.71
4  6287101226916697  Platinum        RuPay        274622        246561.92

  Issued_Date Expiry_Date   Status
0  2015-04-13  2019-10-27  Expired
1  2015-01-27  2018-12-18  Expired
2  2021-06-22  2025-07-19   Active
3  2019-04-04  2023-10-07   Active
4  2023-05-18  2029-08-26  Expired

In [8]:
print(branches.head())

   Branch_ID                       Branch_Name              City  \
0          1  Wang, Mcdonald and Church Branch         Kellitown
1          2            Crawford-Torres Branch       Angelaburgh
2          3                Bridges Inc Branch       Johnsonfort
3          4               Garcia Group Branch      New Kyleberg
4          5  Arroyo, Moore and Freeman Branch  West Coryborough

       Manager_Name  Total_Employees  Branch_Revenue Opening_Date  \
0       Kevin Jones              141     16849288.09   2008-08-01
1     Andrea Steele               39      5822279.32   2015-09-17
2   Michael Coleman              195      2114594.03   2012-07-30
3       Dawn Cooper              144      3390389.63   2018-06-27
4  Samantha Kennedy               42      2771910.11   2012-01-04

   Performance_Rating
0                   2
1                   1
2                   3
3                   2
4                   5

In [9]:
print(support_tickets.head())

  Ticket_ID Customer_ID Account_ID Loan_ID  \
0    T00001       C0478      A1825
1    T00002       C0443      A3583
2    T00003       C0057      A2616     442
3    T00004       C0301      A8786
4    T00005       C0238      A3734

                           Branch_Name                 Issue_Category  \
0               Gonzalez-Martin Branch             Loan Payment Delay
1              Baldwin and Sons Branch               Loan Foreclosure
2    Porter, Osborne and Mendez Branch          Interest Rate Dispute
3  Stafford, Oneal and Williams Branch  Mismatch in Account Statement
4                 Evans-Mercado Branch            KYC Update Required

                                    Description Date_Opened Date_Closed  \
0             Client raised loan payment delay.  2017-09-30  2017-10-24
1               Client raised loan foreclosure.  2015-04-19  2015-05-12
2      Customer reported interest rate dispute.  2016-09-28  2016-10-23
3  Client raised mismatch in account statement.  2019-03-31  2019-04-10
4          System detected kyc update required.  2017-08-11

   Priority       Status              Resolution_Remarks  Support_Agent  \
0       Low       Closed    Card replaced and activated.     Leena Apte
1  Critical  In Progress    Card replaced and activated.   Owen Mahajan
2      High     Resolved          Loan schedule updated.  Wishi Chhabra
3      High       Closed  Pending customer verification.  Gabriel Mutti
4  Critical     Resolved  Pending customer verification.      Ekani Oza

     Channel  Customer_Rating
0      Email                1
1  In-person                1
2      Email                4
3      Email                1
4  In-person                2

In [10]:
customers.isnull().sum()

customer_id     0
name            0
gender          0
age             0
city            0
account_type    0
join_date       0
dtype: int64

In [11]:
accounts.isnull().sum()

customer_id        0
account_balance    0
last_updated       0
dtype: int64

In [12]:
transactions.isnull().sum()

txn_id         0
customer_id    0
txn_type       0
amount         0
txn_time       0
status         0
dtype: int64

In [13]:
loans.isnull().sum()

customer_id     0
name            0
gender          0
age             0
city            0
account_type    0
join_date       0
dtype: int64

In [14]:
credit_cards.isnull().sum()

Card_ID            0
Customer_ID        0
Account_ID         0
Branch             0
Card_Number        0
Card_Type          0
Card_Network       0
Credit_Limit       0
Current_Balance    0
Issued_Date        0
Expiry_Date        0
Status             0
dtype: int64

In [15]:
branches.isnull().sum()

Branch_ID             0
Branch_Name           0
City                  0
Manager_Name          0
Total_Employees       0
Branch_Revenue        0
Opening_Date          0
Performance_Rating    0
dtype: int64

In [16]:
support_tickets.isnull().sum()

Ticket_ID             0
Customer_ID           0
Account_ID            0
Loan_ID               0
Branch_Name           0
Issue_Category        0
Description           0
Date_Opened           0
Date_Closed           0
Priority              0
Status                0
Resolution_Remarks    0
Support_Agent         0
Channel               0
Customer_Rating       0
dtype: int64

In [17]:
conn = sqlite3.connect("bankdata.db")
cursor = conn.cursor()

In [18]:
customers.to_sql("customers",conn,if_exists="replace",index=False)

500

In [19]:
df = pd.read_sql("SELECT * FROM customers", conn) 
df

,customer_id,name,gender,age,city,account_type,join_date
0,C0001,Richard Wilson,M,65,Kimberlyburgh,Savings,2023-08-27
1,C0002,Holly Parker,F,41,Port David,Current,2023-12-08
2,C0003,Megan Alvarez,M,46,West Laurieton,Savings,2022-05-25
3,C0004,Nicholas Stewart,F,39,Amyville,Current,2020-11-30
4,C0005,Douglas Anderson,M,70,New Craigport,Current,2023-01-29
...,...,...,...,...,...,...,...
495,C0496,Jennifer Flores,M,50,Mullenland,Savings,2021-04-03
496,C0497,Melissa Martin,M,41,Shermanfurt,Current,2021-12-27
497,C0498,Christopher Johnson,M,69,Nataliemouth,Savings,2022-10-10
498,C0499,Alvin Compton,M,30,Millerstad,Current,2023-06-16
499,C0500,Emily Brooks,M,47,South Louismouth,Savings,2023-10-11

In [20]:
accounts.to_sql("accounts",conn,if_exists="replace",index=False)

500

In [21]:
df = pd.read_sql("SELECT * FROM accounts", conn) 
df

    customer_id  account_balance         last_updated
0         C0001        293729.87  2025-05-24 09:46:29
1         C0002        150735.15  2025-05-24 09:46:29
2         C0003        170156.21  2025-05-24 09:46:29
3         C0004        311383.96  2025-05-24 09:46:29
4         C0005         60320.75  2025-05-24 09:46:29
..          ...              ...                  ...
495       C0496        149135.80  2025-05-24 09:46:29
496       C0497        376153.36  2025-05-24 09:46:29
497       C0498        320254.17  2025-05-24 09:46:29
498       C0499        484758.19  2025-05-24 09:46:29
499       C0500        454127.94  2025-05-24 09:46:29

[500 rows x 3 columns]

In [22]:
transactions.to_sql("transactions",conn,if_exists="replace",index=False)

10000

In [23]:
df = pd.read_sql("SELECT * FROM transactions", conn) 
df

      txn_id customer_id    txn_type    amount             txn_time   status
0     T00001       C0363     deposit  44442.71  2025-02-14 06:26:00  success
1     T00002       C0432     deposit  15737.59  2025-03-27 07:21:21  success
2     T00003       C0084  withdrawal  82150.70  2024-07-31 18:28:06  success
3     T00004       C0067  withdrawal  20313.86  2024-11-11 12:18:47  success
4     T00005       C0485  withdrawal  74536.08  2025-04-15 10:52:59  success
...      ...         ...         ...       ...                  ...      ...
9995  T09996       C0260  withdrawal  54743.72  2024-07-28 08:41:01  success
9996  T09997       C0172    purchase  13087.77  2024-06-23 07:24:30   failed
9997  T09998       C0494  withdrawal  66846.76  2025-02-10 01:47:28   failed
9998  T09999       C0499  withdrawal  90759.88  2024-12-11 04:45:07  success
9999  T10000       C0201  withdrawal  92878.32  2024-06-27 18:07:13   failed

[10000 rows x 6 columns]

In [24]:
loans.to_sql("loans",conn,if_exists="replace",index=False)

500

In [25]:
df = pd.read_sql("SELECT * FROM loans", conn) 
df

,customer_id,name,gender,age,city,account_type,join_date
0,C0001,Richard Wilson,M,65,Kimberlyburgh,Savings,2023-08-27
1,C0002,Holly Parker,F,41,Port David,Current,2023-12-08
2,C0003,Megan Alvarez,M,46,West Laurieton,Savings,2022-05-25
3,C0004,Nicholas Stewart,F,39,Amyville,Current,2020-11-30
4,C0005,Douglas Anderson,M,70,New Craigport,Current,2023-01-29
...,...,...,...,...,...,...,...
495,C0496,Jennifer Flores,M,50,Mullenland,Savings,2021-04-03
496,C0497,Melissa Martin,M,41,Shermanfurt,Current,2021-12-27
497,C0498,Christopher Johnson,M,69,Nataliemouth,Savings,2022-10-10
498,C0499,Alvin Compton,M,30,Millerstad,Current,2023-06-16
499,C0500,Emily Brooks,M,47,South Louismouth,Savings,2023-10-11

In [26]:
credit_cards.to_sql("credit_cards",conn,if_exists="replace",index=False)

557

In [27]:
df = pd.read_sql("SELECT * FROM credit_cards", conn) 
df

,Card_ID,Customer_ID,Account_ID,Branch,Card_Number,Card_Type,Card_Network,Credit_Limit,Current_Balance,Issued_Date,Expiry_Date,Status
0,1,1559,2090,Perez Ltd Branch,4960013389083863,Business,Visa,178393,39819.23,2015-04-13,2019-10-27,Expired
1,2,1160,2221,Miller Inc Branch,6511615594078161,Platinum,RuPay,416026,175818.58,2015-01-27,2018-12-18,Expired
2,3,1297,2082,"Miles, Patterson and Murray Branch",6316475255341928,Gold,RuPay,419398,29171.29,2021-06-22,2025-07-19,Active
3,4,1333,2058,"Shepard, Gonzales and Cooper Branch",3305641395376724,Gold,Amex,385544,265316.71,2019-04-04,2023-10-07,Active
4,5,1371,2225,Wilson PLC Branch,6287101226916697,Platinum,RuPay,274622,246561.92,2023-05-18,2029-08-26,Expired
...,...,...,...,...,...,...,...,...,...,...,...,...
552,553,1160,2599,"Huff, Bryant and Thomas Branch",6295966048736826,Silver,RuPay,286715,193389.66,2023-06-03,2028-03-08,Active
553,554,1163,2411,Morris-Prince Branch,3865369455158886,Gold,Amex,108003,61642.17,2017-06-13,2021-08-18,Blocked
554,555,1161,2182,"Robertson, Moore and Howell Branch",3640857216966630,Gold,Amex,200094,165305.34,2023-06-27,2029-01-31,Active
555,556,1333,2256,Green-Keith Branch,4297150968832753,Gold,Visa,433856,177349.60,2021-09-21,2027-12-02,Blocked
556,557,1212,2592,"Holmes, Nguyen and French Branch",5773973278195237,Silver,MasterCard,203606,13196.28,2018-08-14,2022-05-11,Active

In [28]:
branches.to_sql("branches",conn,if_exists="replace",index=False)

520

In [29]:
df = pd.read_sql("SELECT * FROM branches", conn) 
df

,Branch_ID,Branch_Name,City,Manager_Name,Total_Employees,Branch_Revenue,Opening_Date,Performance_Rating
0,1,"Wang, Mcdonald and Church Branch",Kellitown,Kevin Jones,141,16849288.09,2008-08-01,2
1,2,Crawford-Torres Branch,Angelaburgh,Andrea Steele,39,5822279.32,2015-09-17,1
2,3,Bridges Inc Branch,Johnsonfort,Michael Coleman,195,2114594.03,2012-07-30,3
3,4,Garcia Group Branch,New Kyleberg,Dawn Cooper,144,3390389.63,2018-06-27,2
4,5,"Arroyo, Moore and Freeman Branch",West Coryborough,Samantha Kennedy,42,2771910.11,2012-01-04,5
...,...,...,...,...,...,...,...,...
515,516,Lowery and Sons Branch,Lake Charles,Daniel Hunt,130,6562890.41,2007-06-22,4
516,517,Brooks Group Branch,New Christina,Rodney Browning,19,19078758.01,2021-07-20,1
517,518,Harris-Marshall Branch,Emilymouth,Lorraine Johnson,177,2801634.32,2011-08-18,5
518,519,"Meadows, Taylor and Butler Branch",Port Michael,David Smith,76,17653138.31,2006-05-21,4
519,520,Beltran-Nelson Branch,Juliabury,Richard Singleton,171,19520645.33,2010-09-13,1

In [31]:
support_tickets.to_sql("support_tickets",conn,if_exists="replace",index=False)

600

In [30]:
df = pd.read_sql("SELECT * FROM support_tickets", conn) 
df

,Ticket_ID,Customer_ID,Account_ID,Loan_ID,Branch_Name,Issue_Category,Description,Date_Opened,Date_Closed,Priority,Status,Resolution_Remarks,Support_Agent,Channel,Customer_Rating
0,T00001,C0478,A1825,,Gonzalez-Martin Branch,Loan Payment Delay,Client raised loan payment delay.,2017-09-30,2017-10-24,Low,Closed,Card replaced and activated.,Leena Apte,Email,1
1,T00002,C0443,A3583,,Baldwin and Sons Branch,Loan Foreclosure,Client raised loan foreclosure.,2015-04-19,2015-05-12,Critical,In Progress,Card replaced and activated.,Owen Mahajan,In-person,1
2,T00003,C0057,A2616,442,"Porter, Osborne and Mendez Branch",Interest Rate Dispute,Customer reported interest rate dispute.,2016-09-28,2016-10-23,High,Resolved,Loan schedule updated.,Wishi Chhabra,Email,4
3,T00004,C0301,A8786,,"Stafford, Oneal and Williams Branch",Mismatch in Account Statement,Client raised mismatch in account statement.,2019-03-31,2019-04-10,High,Closed,Pending customer verification.,Gabriel Mutti,Email,1
4,T00005,C0238,A3734,,Evans-Mercado Branch,KYC Update Required,System detected kyc update required.,2017-08-11,,Critical,Resolved,Pending customer verification.,Ekani Oza,In-person,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,T00596,C0303,A9594,,Johnson Group Branch,Account Frozen,Customer reported account frozen.,2015-03-08,2015-03-30,Medium,Escalated,Issue resolved successfully.,Chaitaly Vaidya,Mobile App,3
596,T00597,C0480,A5144,,Clark Inc Branch,Interest Rate Dispute,Customer reported interest rate dispute.,2020-01-17,2020-01-26,Medium,In Progress,Issue resolved successfully.,Ekapad Jhaveri,In-person,1
597,T00598,C0270,A7108,427,Murphy-Johnston Branch,Interest Rate Dispute,Client raised interest rate dispute.,2016-04-22,2016-05-13,Critical,Resolved,Loan schedule updated.,Advik Bhagat,In-person,4
598,T00599,C0144,A4959,121,"Herrera, Rollins and Hill Branch",Card Not Working,Customer reported card not working.,2015-02-26,2015-03-25,Low,In Progress,Card replaced and activated.,Wriddhish Sarraf,Phone,2
599,T00600,C0076,A7140,24,Peterson-Graves Branch,EMI Auto-debit Failed,Customer reported emi auto-debit failed.,2023-08-19,2023-09-04,Critical,Escalated,Card replaced and activated.,Ria Ghose,Mobile App,5

In [32]:
#Q1: How many customers exist per city, and what is their average account balance?
queries = {
    "Q1": """SELECT c.city, COUNT(DISTINCT c.customer_id) AS total_customers,
                    ROUND (AVG(a.account_balance)) AS avg_balance
            FROM customers c 
            JOIN accounts a ON c.customer_id = a.customer_id
            GROUP BY c.city
            ORDER BY avg_balance DESC LIMIT 10;""",

}

In [33]:
for q , sql in queries.items():
    print(f"\n {q}:")
    try:
        df = pd.read_sql_query(sql, conn)
        print(df.head(10))
    except Exception as e:
        print(f" Error in {q}:{e}")

 Q1:
                 city  total_customers  avg_balance
0     Margaretchester                1     498739.0
1           Kinghaven                1     498317.0
2           Johnmouth                1     494780.0
3          East Robin                1     494700.0
4          Millerstad                1     484758.0
5          Bobbyhaven                1     482746.0
6      Villanuevafurt                1     481747.0
7  North Christinaton                1     479706.0
8          Bryantport                1     477357.0
9          Amandaberg                1     476045.0

In [34]:
#Q2: Which account type (Savings, Current, Loan, etc.) holds the highest total balance?
queries = {
"Q2": """SELECT account_type, 
            SUM(a.account_balance) AS total_balance
            FROM customers c 
            JOIN accounts a ON a.customer_id = c.customer_id
            GROUP BY account_type
            ORDER BY total_balance DESC;"""
}

In [35]:
for q , sql in queries.items():
    print(f"\n {q}:")
    try:
        df = pd.read_sql_query(sql, conn)
        print(df.head(10))
    except Exception as e:
        print(f" Error in {q}:{e}")

 Q2:
  account_type  total_balance
0      Savings    61880483.18
1      Current    61617575.41

In [36]:
#Q3: Who are the top 10 customers by total account balance across all account types?

queries = {
"Q3": """SELECT c.customer_id, c.name, 
            SUM(a.account_balance) AS total_balance
            FROM customers c 
            JOIN accounts a ON a.customer_id = c.customer_id
            GROUP BY c.customer_id, c.name, c.account_type
            ORDER BY total_balance DESC LIMIT 10;"""
}

In [37]:
for q , sql in queries.items():
    print(f"\n {q}:")
    try:
        df = pd.read_sql_query(sql, conn)
        print(df.head(10))
    except Exception as e:
        print(f" Error in {q}:{e}")

 Q3:
  customer_id                name  total_balance
0       C0314          Amy Nguyen      498739.49
1       C0011     Carolyn Higgins      498317.41
2       C0111        Lisa Russell      497040.60
3       C0392      Amber Williams      494779.97
4       C0077         Audrey Peck      494699.91
5       C0499       Alvin Compton      484758.19
6       C0338  Sharon Bennett DVM      482746.37
7       C0317     Denise Campbell      481746.58
8       C0220       Jeffrey Smith      481568.14
9       C0146          Ann Crosby      479706.41

In [38]:
#Q4: Which customers opened accounts in 2023 with a balance above ₹1,00,000?

queries = {
"Q4": """SELECT c.customer_id, c.name, c.city, c.account_type, a.account_balance, c.join_date
            FROM customers c
            JOIN accounts a 
            ON c.customer_id = a.customer_id
            WHERE strftime('%Y', c.join_date) = '2023' 
            AND a.account_balance > 100000
            ORDER BY a.account_balance DESC LIMIT 3;"""
}

In [39]:
for q , sql in queries.items():
    print(f"\n {q}:")
    try:
        df = pd.read_sql_query(sql, conn)
        print(df.head(10))
    except Exception as e:
        print(f" Error in {q}:{e}")

 Q4:
  customer_id             name            city account_type  account_balance  \
0       C0077      Audrey Peck      East Robin      Savings        494699.91
1       C0499    Alvin Compton      Millerstad      Current        484758.19
2       C0317  Denise Campbell  Villanuevafurt      Current        481746.58

    join_date
0  2023-03-21
1  2023-06-16
2  2023-02-08

In [40]:
#Q5: What is the total transaction volume (sum of amounts) by transaction type?
queries = {
"Q5":  """SELECT txn_type, 
            SUM(transactions.amount) AS total_amount
            FROM transactions
            GROUP BY txn_type
            ORDER BY total_amount DESC ;"""
}

In [41]:
for q , sql in queries.items():
    print(f"\n {q}:")
    try:
        df = pd.read_sql_query(sql, conn)
        print(df.head(10))
    except Exception as e:
        print(f" Error in {q}:{e}")

 Q5:
       txn_type  total_amount
0       deposit  1.975748e+08
1    withdrawal  1.513873e+08
2      purchase  7.383403e+07
3      transfer  5.059280e+07
4  online fraud  2.382950e+07

In [42]:
#Q6: Which accounts have more than 3 failed transactions in a single month?
queries = {
"Q6": """SELECT customer_id,
            strftime('%y-%u',txn_time) AS txn_month,
            COUNT(*) AS failed_txn_count
            FROM transactions
            WHERE status = 'failed' 
            GROUP BY customer_id,txn_month
            HAVING COUNT(*)> 3
            ORDER BY failed_txn_count DESC LIMIT 3;"""
}

In [43]:
for q , sql in queries.items():
    print(f"\n {q}:")
    try:
        df = pd.read_sql_query(sql, conn)
        print(df.head(10))
    except Exception as e:
        print(f" Error in {q}:{e}")

 Q6:
  customer_id txn_month  failed_txn_count
0       C0172      None                 9
1       C0035      None                 8
2       C0177      None                 8

In [44]:
#Q7: Which are the top 5 branches by total transaction volume in the last 6 months?
queries = {
"Q7": """SELECT b.branch_id, b.branch_name,
            SUM(t.amount) AS total_volume
            FROM transactions t
            JOIN branches b ON t.customer_id = b.branch_id
            WHERE txn_time >= DATE('now','-6 months')
            GROUP BY b.branch_id, b.branch_name
            ORDER BY total_volume DESC LIMIT 5;"""
}

In [45]:
for q , sql in queries.items():
    print(f"\n {q}:")
    try:
        df = pd.read_sql_query(sql, conn)
        print(df.head(10))
    except Exception as e:
        print(f" Error in {q}:{e}")

 Q7:
Empty DataFrame
Columns: [Branch_ID, Branch_Name, total_volume]
Index: []

In [46]:
#Q8: Which accounts have 5 or more high-value transactions above ₹2,00,000?
queries = {
"Q8": """SELECT customer_id, count(*) AS high_value_txns
            FROM transactions
            WHERE amount>=200000
            GROUP BY customer_id HAVING high_value_txns>=5;"""
}

In [47]:
for q , sql in queries.items():
    print(f"\n {q}:")
    try:
        df = pd.read_sql_query(sql, conn)
        print(df.head(10))
    except Exception as e:
        print(f" Error in {q}:{e}")

 Q8:
Empty DataFrame
Columns: [customer_id, high_value_txns]
Index: []

In [48]:
#Q9: What is the average loan amount and interest rate by loan type (Personal, Auto, Home, etc.)?
queries = {
"Q9": """SELECT loan_type, ROUND(AVG(loan_amount),2) AS avg_loan,
            ROUND(AVG(Interest_Rate),2) AS avg_rate
            FROM loans
            GROUP BY loan_type;"""
}

In [49]:
for q , sql in queries.items():
    print(f"\n {q}:")
    try:
        df = pd.read_sql_query(sql, conn)
        print(df.head(10))
    except Exception as e:
        print(f" Error in {q}:{e}")

 Q9:
 Error in Q9:Execution failed on sql 'SELECT loan_type, ROUND(AVG(loan_amount),2) AS avg_loan,
            ROUND(AVG(Interest_Rate),2) AS avg_rate
            FROM loans
            GROUP BY loan_type;': no such column: loan_type

In [50]:
#Q10: Which customers currently hold more than one active or approved loan?
queries = {
"Q10": """SELECT customer_id, COUNT(*) AS active_lons
            FROM loans
            WHERE loan_status IN ('Approved','Active')
            GROUP BY customer_id HAVING active_lons>1;"""
}

In [51]:
for q , sql in queries.items():
    print(f"\n {q}:")
    try:
        df = pd.read_sql_query(sql, conn)
        print(df.head(10))
    except Exception as e:
        print(f" Error in {q}:{e}")

 Q10:
 Error in Q10:Execution failed on sql 'SELECT customer_id, COUNT(*) AS active_lons
            FROM loans
            WHERE loan_status IN ('Approved','Active')
            GROUP BY customer_id HAVING active_lons>1;': no such column: loan_status

In [52]:
#Q11: Who are the top 5 customers with the highest outstanding (non-closed) loan amounts?
queries = {
"Q11": """SELECT customer_id, SUM(loan_amount) AS total_loan
            FROM loans
            WHERE loan_status='Closed'
            GROUP BY customer_id
            ORDER BY total_loan DESC LIMIT 5;"""
}

In [53]:
for q , sql in queries.items():
    print(f"\n {q}:")
    try:
        df = pd.read_sql_query(sql, conn)
        print(df.head(10))
    except Exception as e:
        print(f" Error in {q}:{e}")

 Q11:
 Error in Q11:Execution failed on sql 'SELECT customer_id, SUM(loan_amount) AS total_loan
            FROM loans
            WHERE loan_status='Closed'
            GROUP BY customer_id
            ORDER BY total_loan DESC LIMIT 5;': no such column: loan_amount

In [54]:
#Q12: Which branch holds the highest total account balance?
queries = {
"Q12": """SELECT account_balance, SUM(account_balance) AS total_balance
            FROM accounts
            GROUP BY account_balance
            ORDER BY total_balance DESC LIMIT 3;"""
}

In [55]:
for q , sql in queries.items():
    print(f"\n {q}:")
    try:
        df = pd.read_sql_query(sql, conn)
        print(df.head(10))
    except Exception as e:
        print(f" Error in {q}:{e}")

 Q12:
   account_balance  total_balance
0        498739.49      498739.49
1        498317.41      498317.41
2        497040.60      497040.60

In [56]:
#Q13: What is the branch performance summary showing total customers, total loans, and transaction volume?
queries = {
"Q13": """SELECT b.Branch_Name,
            COUNT(DISTINCT a.customer_id) AS total_customers,
            COUNT(DISTINCT l.Loan_ID) AS total_loans,
            ROUND(SUM(a.account_balance),2) AS total_balance
            FROM branches b
            LEFT JOIN accounts a ON b.Branch_ID = a.customer_id
            LEFT JOIN loans l ON a.customer_id  = l.Customer_ID 
            GROUP BY b.Branch_Name
            ORDER BY total_balance DESC LIMIT 10;"""
}

In [57]:
for q , sql in queries.items():
    print(f"\n {q}:")
    try:
        df = pd.read_sql_query(sql, conn)
        print(df.head(10))
    except Exception as e:
        print(f" Error in {q}:{e}")

 Q13:
 Error in Q13:Execution failed on sql 'SELECT b.Branch_Name,
            COUNT(DISTINCT a.customer_id) AS total_customers,
            COUNT(DISTINCT l.Loan_ID) AS total_loans,
            ROUND(SUM(a.account_balance),2) AS total_balance
            FROM branches b
            LEFT JOIN accounts a ON b.Branch_ID = a.customer_id
            LEFT JOIN loans l ON a.customer_id  = l.Customer_ID
            GROUP BY b.Branch_Name
            ORDER BY total_balance DESC LIMIT 10;': no such column: l.Loan_ID

In [58]:
#Q14: Which issue categories have the longest average resolution time?
queries = {
"Q14": """SELECT issue_category,
            ROUND(AVG(julianday(Date_Closed)-julianday(Date_Opened)),2) AS avg_days, COUNT(*) AS total_tickets
            FROM support_tickets
            WHERE Date_Closed!=''
            GROUP BY issue_category
            ORDER BY avg_days DESC LIMIT 10;"""
}

In [59]:
for q , sql in queries.items():
    print(f"\n {q}:")
    try:
        df = pd.read_sql_query(sql, conn)
        print(df.head(10))
    except Exception as e:
        print(f" Error in {q}:{e}")

 Q14:
                  Issue_Category  avg_days  total_tickets
0               Card Not Working     18.50             16
1  Mismatch in Account Statement     17.90             31
2      Debit Card Delivery Delay     17.81             27
3             UPI Payment Failed     17.46             24
4        Account Closure Request     17.32             31
5                 Account Frozen     17.12             26
6               Loan Foreclosure     16.58             60
7                  Cheque Bounce     16.00             27
8          EMI Auto-debit Failed     15.98             42
9         Online Transfer Failed     15.48             21

In [60]:
#Q15: Which support agents have resolved the most critical tickets with high customer ratings (≥4)?
queries = {
"Q15": """SELECT Support_Agent, COUNT(*) AS resolve_tickets
            FROM support_tickets
            WHERE Priority = 'Critical' AND Customer_Rating >=4
            GROUP BY Support_Agent
            ORDER BY resolve_tickets DESC LIMIT 5;"""
}

In [61]:
for q , sql in queries.items():
    print(f"\n {q}:")
    try:
        df = pd.read_sql_query(sql, conn)
        print(df.head(10))
    except Exception as e:
        print(f" Error in {q}:{e}")

 Q15:
      Support_Agent  resolve_tickets
0      Owen Mahajan                7
1  Wriddhish Sarraf                6
2       Ranveer Roy                6
3     Chanakya Natt                5
4     Gabriel Mutti                4

In [364]:
%%writefile app.py
import streamlit as st
st.write("hello")

Overwriting app.py